name: Scheduled Trigger for 1.4
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 #v4
      - name: Trigger main build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run MainDistributionPipeline.yml --ref main
